---
name: "Dokku"
description: "Official Github Action for deploying apps to a Dokku installation"
author: "Dokku"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  branch:
    description: "The branch to deploy when pushing to Dokku (default: master)"
    required: false
    default: "master"
  ci_branch_name:
    description: "The command to run for the action (default: detected from GITHUB_REF)"
    required: false
    default: ""
  ci_commit:
    description: "The commit sha that will be pushed (default: detected from GITHUB_SHA)"
    required: false
    default: ""
  command:
    description: "The command to run for the action (default: deploy)"
    required: false
    default: "deploy"
  git_push_flags:
    description: "A string containing a set of flags to set on push"
    required: false
    default: ""
  git_remote_url:
    description: "The dokku app's git repository url (in SSH format)"
    required: true
  review_app_name:
    description: "The name of the review app to create or destroy"
    required: false
    default: ""
  ssh_host_key:
    description: "The results of running `ssh-keyscan -t rsa $HOST`"
    required: false
    default: ""
  ssh_private_key:
    description: "A private SSH key that has push acces to your Dokku instance"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/bin/dokku-deploy"
  post-entrypoint: "/bin/dokku-unlock"
  post-if: cancelled()
  env:
    BRANCH: ${{ inputs.branch }}
    CI_BRANCH_NAME: ${{ inputs.ci_branch_name }}
    CI_COMMIT: ${{ inputs.ci_commit }}
    COMMAND: ${{ inputs.command }}
    GIT_PUSH_FLAGS: ${{ inputs.git_push_flags }}
    GIT_REMOTE_URL: ${{ inputs.git_remote_url }}
    REVIEW_APP_NAME: ${{ inputs.review_app_name }}
    SSH_HOST_KEY: ${{ inputs.ssh_host_key }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
